#!/bin/bash
# school; displays days left in school

START=$(date --date="2016-01-25")
NOW=$(date)
END=$(date --date="2016-05-20")

TOTAL=$(echo "(`date -d "$END" +%s` - `date -d "$START" +%s`) / (24*3600)" | bc -l)
COMPLETE=$(echo "(`date -d "$NOW" +%s` - `date -d "$START" +%s`) / (24*3600)" | bc -l)
PERCENT=$(echo "scale=2; 100 * $COMPLETE / $TOTAL" | bc -l)

echo "$PERCENT%"
