command_timeout = 200

format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character"""

[directory]
truncation_length = 3

[git_status]
format = '([$all_status$ahead_behind]($style) )'

[cmd_duration]
min_time = 2_000
format = "took [$duration]($style) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
